### ISSUE TITLE
getLocalPage()获取的page对象为null

### ISSUE THREAD

**Issue by Edgar-cn** [pagehelper/pagehelper-spring-boot#108]
- 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* 最新版本
#### 定位到的代码部分

```java
        String sql = boundSql.getSql();
        Page page = getLocalPage();
        //支持 order by
        String orderBy = page.getOrderBy();
```

### 完整异常信息

```
java.lang.NullPointerException: null
	at com.github.pagehelper.dialect.AbstractHelperDialect.getPageSql(AbstractHelperDialect.java:188)
	at com.github.pagehelper.PageHelper.getPageSql(PageHelper.java:101)
	at com.github.pagehelper.util.ExecutorUtil.pageQuery(ExecutorUtil.java:196)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:107)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy143.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy89.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy98.findList(Unknown Source)
	at com.sunnyit.safe.core.persistence.BaseService.findPage(BaseService.java:72)
	at com.sunnyit.safe.core.persistence.BaseService$$FastClassBySpringCGLIB$$9ab2108e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)

```

### 错误描述
’‘’
在分页查询的时候，偶尔会出现上面的错误
 getLocalPage()获取的Page对象为null
所以再执行下一步   page.getOrderBy()   的时候抛出空指针异常
’‘’

**Comment by abel533** [comment]
可以复现吗？
理论上能走到这个方法，前面肯定获取到page了。

这个问题是正常运行出现，还是debug出现？
