### ISSUE TITLE
1.30版本报错net.sf.jsqlparser.statement.select.PlainSelect.getGroupBy() 回退1.2.3正常

### ISSUE THREAD

**Issue by xxh1998** [pagehelper/pagehelper-spring-boot#114]
java.lang.NoSuchMethodError: net.sf.jsqlparser.statement.select.PlainSelect.getGroupBy()Lnet/sf/jsqlparser/statement/select/GroupByElement;

	at com.github.pagehelper.parser.CountSqlParser.isSimpleCount(CountSqlParser.java:259)
	at com.github.pagehelper.parser.CountSqlParser.sqlToCount(CountSqlParser.java:238)
	at com.github.pagehelper.parser.CountSqlParser.getSmartCountSql(CountSqlParser.java:197)
	at com.github.pagehelper.parser.CountSqlParser.getSmartCountSql(CountSqlParser.java:162)
	at com.github.pagehelper.dialect.helper.SqlServerDialect.getCountSql(SqlServerDialect.java:64)
	at com.github.pagehelper.PageHelper.getCountSql(PageHelper.java:81)
	at com.github.pagehelper.util.ExecutorUtil.executeAutoCount(ExecutorUtil.java:154)
	at com.github.pagehelper.PageInterceptor.count(PageInterceptor.java:157)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:100)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy270.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy121.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.executeForMany(PageMapperMethod.java:173)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.execute(PageMapperMethod.java:86)

代码
        private static int PAGE_SIZE = 5000;
        QueryWrapper<InventoryDO> queryWrapper = new QueryWrapper<>();
        queryWrapper.gt("RV", fromRV);
        queryWrapper.gt("QtyOnHand",0);
        PageHelper.startPage(1, PAGE_SIZE);
        List<InventoryDO> inventorys;
        inventorys = inventoryMapper.selectList(queryWrapper);

版本 spring boot 采用 2.1.9 版本   数据库sqlserver  
<mybatis-start.version>2.1.3</mybatis-start.version>
        <mybatis.plus.version>3.0.7.1</mybatis.plus.version>
        <pagehelper.version>1.3.0</pagehelper.version>

**Comment by HeyChiang** [comment]
我遇到了同样的问题，使用的MySQL数据库，退回1.2.5就正常了
