### ISSUE TITLE
MS-SQL不支持分页

### ISSUE THREAD

**Issue by smaiiboy** [pagehelper/pagehelper-spring-boot#12]
```
### SQL: select count(0) from (SELECT * FROM (         select T_SYSTEM_USER.*,'' AS RoleGuid,'' AS RoleName,'' as DeptGuid, DeptName = (stuff((select ',' + deptname         from T_SYSTEM_Department a inner join         T_SYSTEM_DeptUser_Relation b on a.DeptGuid=b.DeptGuid where b.UserGuid = T_SYSTEM_USER.UserGuid for xml         path('')),1,1,'')) from T_SYSTEM_USER         ) a          WHERE a.DelFlag != 1             AND             a.Isforbid != 1) tmp_count
### Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!] with root cause
```
但是手动查数量以及ROW_NUMBER()可以查询

**Comment by abel533** [comment]
这是完整的错误信息吗？ 上面的count查询sql测试过吗？

**Comment by smaiiboy** [comment]
```
### Error querying database.  Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!
### The error may exist in file [D:\Company\Expsoft\project\Expsoft_JavaOA\target\classes\sql\SysUser.xml]
### The error may involve cn.expsoft.system.dao.SysUserDAO.getListByRoleOrDept_COUNT
### The error occurred while handling results
### SQL: select count(0) from (select T_SYSTEM_USER.*,'' AS RoleGuid,'' AS RoleName,'' as DeptGuid, DeptName = (stuff((select ',' + deptname         from T_SYSTEM_Department a inner join         T_SYSTEM_DeptUser_Relation b on a.DeptGuid=b.DeptGuid where b.UserGuid = T_SYSTEM_USER.UserGuid for xml         path('')),1,1,'')) from T_SYSTEM_USER          WHERE DelFlag != 1             AND             Isforbid != 1) tmp_count
### Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!] with root cause
com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!
	at com.github.pagehelper.parser.SqlServerParser.convertToPageSql(SqlServerParser.java:105)
	at com.github.pagehelper.dialect.helper.SqlServerDialect.getPageSql(SqlServerDialect.java:76)
	at com.github.pagehelper.dialect.AbstractHelperDialect.getPageSql(AbstractHelperDialect.java:112)
	at com.github.pagehelper.PageHelper.getPageSql(PageHelper.java:97)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:128)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy105.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy62.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy71.getListByRoleOrDept(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy72.getListByRoleOrDept(Unknown Source)
	at cn.expsoft.system.service.impl.SysUserServiceImpl.getListByRoleOrDept(SysUserServiceImpl.java:130)
	at cn.expsoft.system.service.impl.SysUserServiceImpl$$FastClassBySpringCGLIB$$135189bd.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669)
	at cn.expsoft.system.service.impl.SysUserServiceImpl$$EnhancerBySpringCGLIB$$7db8296c.getListByRoleOrDept(<generated>)
	at cn.expsoft.system.controller.admin.SysUserCtrl.list(SysUserCtrl.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

```
测试过

```
 SELECT
        TOP ${limit} *
        FROM
        (
        select  ROW_NUMBER()
        OVER (
        ORDER BY SortSQ DESC ) AS RowNumber,
        T_SYSTEM_USER.*,'' AS RoleGuid,'' AS RoleName,'' as DeptGuid, DeptName = (stuff((select ',' + deptname
        from T_SYSTEM_Department a inner join
        T_SYSTEM_DeptUser_Relation b on a.DeptGuid=b.DeptGuid where b.UserGuid = T_SYSTEM_USER.UserGuid for xml
        path('')),1,1,'')) from T_SYSTEM_USER
        <where>
            DelFlag != 1
            AND
            Isforbid != 1

            <if test="query1!=null and query1 !=''">
                AND ChineseName LIKE '%'+#{query1}+'%'
            </if>
            <if test="query3!=null and query3 !=''">
                AND DeptName LIKE '%'+#{query3}+'%'
            </if>
            <!--<if test="query2!=null and query2 != ''">
                AND T_Role.RoleType = #{query2}
            </if>-->
        </where>
        ) AS B
        WHERE
        RowNumber > #{offset}
```
这种的可以运行

**Comment by brantroy** [comment]
是JSqlParser的问题：Refer To https://github.com/JSQLParser/JSqlParser/issues/479
解决方式：在pom.xml中execlusive了JSqlParser，然后引入最新的JsqlParser
