### ISSUE TITLE
SQLServer中关键字使用中括号[RULE]报错

### ISSUE THREAD

**Issue by ice-lucky** [pagehelper/pagehelper-spring-boot#139]
select count(0) from (SELECT id, [RULE] FROM TBL where t=0) tmp_count
Exception
`### Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!
at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.5.4.jar:3.5.4]
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149) ~[mybatis-3.5.4.jar:3.5.4]
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[mybatis-3.5.4.jar:3.5.4]
at sun.reflect.GeneratedMethodAccessor366.invoke(Unknown Source) ~[na:na]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) ~[mybatis-spring-2.0.4.jar:2.0.4]
... 112 common frames omitted
Caused by: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!
at com.github.pagehelper.parser.SqlServerParser.convertToPageSql(SqlServerParser.java:106) ~[pagehelper-5.1.11.jar:na]
at com.github.pagehelper.dialect.helper.SqlServerDialect.getPageSql(SqlServerDialect.java:84) ~[pagehelper-5.1.11.jar:na]
at com.github.pagehelper.dialect.helper.SqlServerDialect.getPageSql(SqlServerDialect.java:112) ~[pagehelper-5.1.11.jar:na]

使用的是 pagehelper-springboot-starter 的方式，代码基本无额外配置。

JSqlParser相关issue查看可通过以下方式解决，请问下PageHelper需要怎么处理？
`CCJSqlParserUtil.parse("select [RULE] from TBL", parser -> parser.withSquareBracketQuotation(true));`

[JSqlParser issues#1117](https://github.com/JSQLParser/JSqlParser/issues/1117)

**Comment by abel533** [comment]
目前还在支持jdk6，所以jdk8的功能还用不了，等最近先限制order by发版后，开始基于jdk8进行升级。

**Comment by ice-lucky** [comment]
可否调整增加支持外部自定义 SQLParser 的方式？  由外部重写SqlServerParser.convertToPageSql(..)方式解决

**Comment by abel533** [comment]
外部可以重写 dialect，可能涉及多个类。

**Comment by abel533** [comment]
增加了一个接口用于自定义：
```java
package com.github.pagehelper;

import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.statement.Statement;

/**
 * 为了兼容不同版本 jdk 和 jsqlparser
 * <p>
 * 使用 sqlserver 时，可以使用下面方式支持 `[]`
 * <pre>
 * JSqlParser SQLSERVER_PARSER = new JSqlParser() {
 *      @Override
 *      public Statement parse(String statementReader) throws JSQLParserException {
 *          return CCJSqlParserUtil.parse(statementReader, parser -> parser.withSquareBracketQuotation(true));
 *      }
 *  }
 *  </pre>
 *
 * @author liuzh
 */
public interface JSqlParser {

    /**
     * 默认实现
     */
    JSqlParser DEFAULT = new JSqlParser() {
        @Override
        public Statement parse(String statementReader) throws JSQLParserException {
            return CCJSqlParserUtil.parse(statementReader);
        }
    };

    /**
     * 解析 SQL
     *
     * @param statementReader SQL
     * @return
     * @throws JSQLParserException
     */
    Statement parse(String statementReader) throws JSQLParserException;

}

```
