### ISSUE TITLE
Springboot1.5.10 启动报错

### ISSUE THREAD

**Issue by chenzhenhu** [pagehelper/pagehelper-spring-boot#36]
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at org.apache.ibatis.mapping.CacheBuilder.setCacheProperties(CacheBuilder.java:147) ~[mybatis-3.4.5.jar:3.4.5]
	at org.apache.ibatis.mapping.CacheBuilder.build(CacheBuilder.java:95) ~[mybatis-3.4.5.jar:3.4.5]
	at com.github.pagehelper.cache.SimpleCache.<init>(SimpleCache.java:74) ~[pagehelper-5.1.2.jar:na]
	at com.github.pagehelper.cache.CacheFactory.createCache(CacheFactory.java:52) ~[pagehelper-5.1.2.jar:na]
	at com.github.pagehelper.PageInterceptor.setProperties(PageInterceptor.java:233) ~[pagehelper-5.1.2.jar:na]
	at com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration.addPageInterceptor(PageHelperAutoConfiguration.java:78) ~[pagehelper-spring-boot-autoconfigure-1.2.3.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 23 common frames omitted

**Comment by abel533** [comment]
配置了什么参数？

**Comment by chenzhenhu** [comment]
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

我的项目是多模块

**Comment by chenzhenhu** [comment]
加上 google guava 就好了
